### ISSUE TITLE
Open install.html on installation

### ISSUE THREAD

**Issue by Arihant25** [Arihant25/class-link-check#1]

**Comment by Arihant25** [comment]
@AmiMappy Kindly fix this so that v0.0.0.3 can be released.

**Comment by AmiMappy** [comment]
Ok

**Comment by AmiMappy** [comment]
We won't distribute index.html and readme with the extension right?

**Comment by Arihant25** [comment]
No, we won’t.

**Comment by AmiMappy** [comment]
ok

**Comment by AmiMappy** [comment]
![image](https://user-images.githubusercontent.com/40239457/121507466-487f9c00-ca02-11eb-975d-10b3768f134c.png)

the donate button doesn't show up because I think chrome extensions content security policy doesn't allow for loading of remote scripts like the one you bring for donation button. Change that.

**Comment by AmiMappy** [comment]
I have a better solution which I will add with the final commit
